/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package intelligent.planning.pkgfor.academics;

import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jusername = new javax.swing.JLabel();
        jpassword = new javax.swing.JLabel();
        typeuser = new javax.swing.JTextField();
        blogin = new javax.swing.JButton();
        bsignup = new javax.swing.JButton();
        bforgotp = new javax.swing.JButton();
        jlogin = new javax.swing.JLabel();
        bexit = new javax.swing.JLabel();
        typepassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        checkbox = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setText("LOGIN");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        jLabel2.setText("USERNAME");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 80, 30));

        jLabel3.setBackground(new java.awt.Color(240, 240, 240));
        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("x");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\undraw_building_websites_i78t.png")); // NOI18N
        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setLayout(null);

        jusername.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jusername.setText("USERNAME :");
        jPanel3.add(jusername);
        jusername.setBounds(90, 130, 110, 20);

        jpassword.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jpassword.setText("PASSWORD :");
        jPanel3.add(jpassword);
        jpassword.setBounds(90, 200, 120, 18);

        typeuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeuserActionPerformed(evt);
            }
        });
        jPanel3.add(typeuser);
        typeuser.setBounds(230, 130, 220, 30);

        blogin.setBackground(new java.awt.Color(102, 255, 255));
        blogin.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        blogin.setText("LOGIN");
        blogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 3, true));
        blogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bloginMouseClicked(evt);
            }
        });
        blogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloginActionPerformed(evt);
            }
        });
        jPanel3.add(blogin);
        blogin.setBounds(110, 330, 120, 40);

        bsignup.setBackground(new java.awt.Color(102, 255, 255));
        bsignup.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        bsignup.setText("SIGN UP");
        bsignup.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 3, true));
        bsignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bsignupMouseClicked(evt);
            }
        });
        bsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsignupActionPerformed(evt);
            }
        });
        jPanel3.add(bsignup);
        bsignup.setBounds(110, 390, 120, 40);

        bforgotp.setBackground(new java.awt.Color(102, 255, 255));
        bforgotp.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        bforgotp.setText("forgot password ?");
        bforgotp.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 255)));
        bforgotp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bforgotpMouseClicked(evt);
            }
        });
        jPanel3.add(bforgotp);
        bforgotp.setBounds(90, 500, 150, 22);

        jlogin.setBackground(new java.awt.Color(255, 255, 255));
        jlogin.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jlogin.setLabelFor(jlogin);
        jlogin.setText("LOGIN !");
        jPanel3.add(jlogin);
        jlogin.setBounds(280, 20, 160, 30);

        bexit.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bexit.setForeground(new java.awt.Color(204, 0, 0));
        bexit.setText("x");
        bexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bexitMouseClicked(evt);
            }
        });
        jPanel3.add(bexit);
        bexit.setBounds(710, 0, 20, 20);

        typepassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typepasswordActionPerformed(evt);
            }
        });
        jPanel3.add(typepassword);
        typepassword.setBounds(230, 190, 220, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\icons8_Forgot_Password_50px_4.png")); // NOI18N
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 480, 50, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\icons8_Secure_50px.png")); // NOI18N
        jPanel3.add(jLabel7);
        jLabel7.setBounds(30, 190, 50, 50);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\icons8_Account_50px.png")); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(30, 120, 50, 50);

        checkbox.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        checkbox.setText("show password");
        checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxActionPerformed(evt);
            }
        });
        jPanel3.add(checkbox);
        checkbox.setBounds(340, 230, 146, 22);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/loginpage.png"))); // NOI18N
        jPanel3.add(jLabel5);
        jLabel5.setBounds(260, 180, 690, 510);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Arrowback.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel9);
        jLabel9.setBounds(10, 10, 37, 20);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 640));

        setSize(new java.awt.Dimension(730, 640));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void typeuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeuserActionPerformed

    private void bsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bsignupActionPerformed

    private void bloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloginActionPerformed
        // TODO add your handling code here:
        String username = typeuser.getText();
        String password = typepassword.getText();
        if("user".equals(username)&& "6124".equals(password))
        {
            welcome wel = new welcome();
        wel.setVisible(true);
        this.dispose();
        } 
        else
        {
            JOptionPane.showMessageDialog(this, "INVALID USERNAME OR PASSWORD" + "");
        }
    }//GEN-LAST:event_bloginActionPerformed

    private void bexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bexitMouseClicked
System.exit(0);       // TODO add your handling code here:
    }//GEN-LAST:event_bexitMouseClicked

    private void typepasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typepasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typepasswordActionPerformed

    private void checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxActionPerformed
        
    // TODO add your handling code here:
    if(checkbox.isSelected())
        {
            typepassword.setEchoChar((char)0);
        }
        else
        {
          typepassword.setEchoChar('*');
        }
    }//GEN-LAST:event_checkboxActionPerformed

    private void bsignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bsignupMouseClicked
        // TODO add your handling code here:
        
       signuppage signup = new signuppage();
        
        signup.setVisible(true);
        this.dispose();
       
        
    }//GEN-LAST:event_bsignupMouseClicked

    private void bforgotpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bforgotpMouseClicked
        // TODO add your handling code here:
        
      forgotpasswordpg  forgotp = new forgotpasswordpg();
        
        forgotp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bforgotpMouseClicked

    private void bloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bloginMouseClicked
        // TODO add your handling code here:
        welcome wel = new welcome();
        wel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bloginMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        homepage hp = new homepage();
        hp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bexit;
    private javax.swing.JButton bforgotp;
    private javax.swing.JButton blogin;
    private javax.swing.JButton bsignup;
    private javax.swing.JCheckBox checkbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jlogin;
    private javax.swing.JLabel jpassword;
    private javax.swing.JLabel jusername;
    private javax.swing.JPasswordField typepassword;
    private javax.swing.JTextField typeuser;
    // End of variables declaration//GEN-END:variables
}
