/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package intelligent.planning.pkgfor.academics;

/**
 *
 * @author Admin
 */
public class planyourfuture extends javax.swing.JFrame {

    /**
     * Creates new form planyourfuture
     */
    public planyourfuture() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        lback = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        qualification = new javax.swing.JPanel();
        iconq = new javax.swing.JLabel();
        l10mark = new javax.swing.JLabel();
        l12mark = new javax.swing.JLabel();
        ldegree = new javax.swing.JLabel();
        lscholar = new javax.swing.JLabel();
        leducamp = new javax.swing.JLabel();
        lolympaid = new javax.swing.JLabel();
        txt10mark = new javax.swing.JTextField();
        txt12mark = new javax.swing.JTextField();
        txtdegree = new javax.swing.JTextField();
        txtscholar = new javax.swing.JTextField();
        txteducamp = new javax.swing.JTextField();
        txtolympaid = new javax.swing.JTextField();
        combo12 = new javax.swing.JComboBox<>();
        combod = new javax.swing.JComboBox<>();
        interest = new javax.swing.JPanel();
        iconin = new javax.swing.JLabel();
        lindoor = new javax.swing.JLabel();
        loutdoor = new javax.swing.JLabel();
        lcultural = new javax.swing.JLabel();
        lbook = new javax.swing.JLabel();
        lcontent = new javax.swing.JLabel();
        cin = new javax.swing.JComboBox<>();
        cout = new javax.swing.JComboBox<>();
        ccultural = new javax.swing.JComboBox<>();
        cbookin = new javax.swing.JComboBox<>();
        ccontent = new javax.swing.JComboBox<>();
        communication = new javax.swing.JPanel();
        q1 = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        q2 = new javax.swing.JLabel();
        r4 = new javax.swing.JRadioButton();
        r5 = new javax.swing.JRadioButton();
        r6 = new javax.swing.JRadioButton();
        q3 = new javax.swing.JLabel();
        r7 = new javax.swing.JRadioButton();
        r8 = new javax.swing.JRadioButton();
        r9 = new javax.swing.JRadioButton();
        q4 = new javax.swing.JLabel();
        r10 = new javax.swing.JRadioButton();
        r11 = new javax.swing.JRadioButton();
        r12 = new javax.swing.JRadioButton();
        q5 = new javax.swing.JLabel();
        r13 = new javax.swing.JRadioButton();
        r14 = new javax.swing.JRadioButton();
        r15 = new javax.swing.JRadioButton();
        financial = new javax.swing.JPanel();
        lbudget = new javax.swing.JLabel();
        cbudget = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        mat = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PLAN YOUR FUTURE");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(445, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(344, 344, 344))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 40));

        jPanel5.setBackground(java.awt.Color.orange);

        jButton1.setBackground(java.awt.Color.orange);
        jButton1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton1.setText("QAULIFICATION");
        jButton1.setBorder(new javax.swing.border.LineBorder(java.awt.Color.orange, 1, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(java.awt.Color.orange);
        jButton2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton2.setText("INTEREST/HOBBY");
        jButton2.setBorder(new javax.swing.border.LineBorder(java.awt.Color.orange, 1, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(java.awt.Color.orange);
        jButton3.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jButton3.setText("COMMUNICATION SKILL");
        jButton3.setBorder(new javax.swing.border.LineBorder(java.awt.Color.orange, 1, true));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(java.awt.Color.orange);
        jButton4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton4.setText("MENTAL ABILITY TEST");
        jButton4.setBorder(new javax.swing.border.LineBorder(java.awt.Color.orange, 1, true));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(java.awt.Color.orange);
        jButton5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton5.setText("FINANCIAL ANALYSIS");
        jButton5.setBorder(new javax.swing.border.LineBorder(java.awt.Color.orange, 1, true));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        lback.setForeground(new java.awt.Color(255, 255, 255));
        lback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Arrowback.png"))); // NOI18N
        lback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(lback)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(lback)
                .addGap(37, 37, 37)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 160, 690));

        qualification.setBackground(new java.awt.Color(255, 255, 255));

        iconq.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/certificate1.png"))); // NOI18N

        l10mark.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        l10mark.setText("Enter 10th marks");

        l12mark.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        l12mark.setText("Enter 12th marks");

        ldegree.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        ldegree.setText("Degree");

        lscholar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lscholar.setText("Any Scholarships attempted");

        leducamp.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        leducamp.setText("Any educational camp attempted");

        lolympaid.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lolympaid.setText("Any Olympaid");

        txt10mark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt10markActionPerformed(evt);
            }
        });

        txtscholar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtscholarActionPerformed(evt);
            }
        });

        combo12.setFont(new java.awt.Font("Century", 0, 12)); // NOI18N
        combo12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "SCIENCE", "COMMERCE", "ARTS", " " }));

        combod.setFont(new java.awt.Font("Century", 0, 12)); // NOI18N
        combod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "M.COM", "MBA", "MCA", "MSC-IT", "MTECH", " " }));

        javax.swing.GroupLayout qualificationLayout = new javax.swing.GroupLayout(qualification);
        qualification.setLayout(qualificationLayout);
        qualificationLayout.setHorizontalGroup(
            qualificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qualificationLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(qualificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(qualificationLayout.createSequentialGroup()
                        .addGroup(qualificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(qualificationLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lolympaid))
                            .addComponent(leducamp))
                        .addGap(61, 61, 61)
                        .addGroup(qualificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt10mark, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(qualificationLayout.createSequentialGroup()
                                .addGroup(qualificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt12mark, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(txtdegree)
                                    .addComponent(txtscholar)
                                    .addComponent(txteducamp)
                                    .addComponent(txtolympaid))
                                .addGap(67, 67, 67)
                                .addGroup(qualificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combod, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combo12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, qualificationLayout.createSequentialGroup()
                        .addGroup(qualificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lscholar)
                            .addComponent(ldegree)
                            .addComponent(l12mark)
                            .addComponent(l10mark))
                        .addGap(561, 561, 561))))
            .addGroup(qualificationLayout.createSequentialGroup()
                .addGap(413, 413, 413)
                .addComponent(iconq, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        qualificationLayout.setVerticalGroup(
            qualificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qualificationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconq, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(qualificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l10mark)
                    .addComponent(txt10mark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(qualificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l12mark)
                    .addComponent(txt12mark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(qualificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ldegree)
                    .addComponent(txtdegree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(qualificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lscholar)
                    .addComponent(txtscholar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(qualificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leducamp)
                    .addComponent(txteducamp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(qualificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtolympaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lolympaid))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", qualification);

        interest.setBackground(new java.awt.Color(255, 255, 255));

        iconin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hobbies1.png"))); // NOI18N

        lindoor.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lindoor.setText("INDOOR SPORTS");

        loutdoor.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        loutdoor.setText("OUTDOOR SPORTS");

        lcultural.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lcultural.setText("CLUTURAL");

        lbook.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lbook.setText("BOOK INTEREST");

        lcontent.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lcontent.setText("CONTENT CREATION");

        cin.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE ", "CARROM", "UNO", "CHESS", "CARDS", " " }));

        cout.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cout.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "BATMINTON", "CRICKET", "HOCKEY", "VOLLEYBALL", "SKATING", "FOOTBALL", "BASKETBALL", "KABADDI", " " }));

        ccultural.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ccultural.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "DANCE", "SINGING", "INSTRUMENT", " ", " " }));

        cbookin.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cbookin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "SCI-FI", "BIOPIC", "NOVEL", "STORY" }));

        ccontent.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ccontent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "DESIGNING", "VLOG", " " }));

        javax.swing.GroupLayout interestLayout = new javax.swing.GroupLayout(interest);
        interest.setLayout(interestLayout);
        interestLayout.setHorizontalGroup(
            interestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, interestLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconin, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(374, 374, 374))
            .addGroup(interestLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(interestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loutdoor)
                    .addComponent(lindoor)
                    .addComponent(lcultural)
                    .addComponent(lbook)
                    .addComponent(lcontent))
                .addGap(138, 138, 138)
                .addGroup(interestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ccontent, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cin, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ccultural, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbookin, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(383, Short.MAX_VALUE))
        );
        interestLayout.setVerticalGroup(
            interestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, interestLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(iconin)
                .addGap(85, 85, 85)
                .addGroup(interestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(interestLayout.createSequentialGroup()
                        .addGroup(interestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lindoor))
                        .addGap(62, 62, 62)
                        .addGroup(interestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loutdoor)
                            .addComponent(cout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78)
                        .addComponent(lcultural))
                    .addComponent(ccultural, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(interestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbook)
                    .addComponent(cbookin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(interestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lcontent)
                    .addComponent(ccontent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114))
        );

        jTabbedPane1.addTab("tab2", interest);

        communication.setBackground(new java.awt.Color(255, 255, 255));

        q1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        q1.setText("1. When writing professional emails, which approach do you prefer ?");

        r1.setText("keeping them concise and to the point");

        r2.setText("providing detailed explanations and context");
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });

        r3.setText("tailoring the tone and content based on the recipient's preferences");
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });

        q2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        q2.setText("2. When giving a presentation, what is your approach to engaging the audience ?");

        r4.setText("focus on data and fact make a compelling case");

        r5.setText("use stories,visuals, and anecedotes take it relatable");
        r5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5ActionPerformed(evt);
            }
        });

        r6.setText("interact with the audience, ask questions, and courage participation");
        r6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r6ActionPerformed(evt);
            }
        });

        q3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        q3.setText("3. How do you respond to constructive feedback from your superiors ?");

        r7.setText("become defencive and resist the feedback");
        r7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r7ActionPerformed(evt);
            }
        });

        r8.setText("acknowledge the feedback and work on improvements");

        r9.setText("seek clarification and additional guidance to better understand the feedback");

        q4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        q4.setText("4. How do you prepare for important conversation or negotiations?");

        r10.setText("develop a clear agenda and strategy in advance");

        r11.setText("trust your instincts and adapt on the spot");

        r12.setText("collaborate with others to brainstrom approaches");

        q5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        q5.setText("5. When delivering feedback to a colleague, what is a preferred approach?");

        r13.setText("be direct and straight forward");

        r14.setText("offer feedback in a gentle and diplomatic manner");

        r15.setText("start with positive feedback before addressing areas of improvement");

        javax.swing.GroupLayout communicationLayout = new javax.swing.GroupLayout(communication);
        communication.setLayout(communicationLayout);
        communicationLayout.setHorizontalGroup(
            communicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(communicationLayout.createSequentialGroup()
                .addGroup(communicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(communicationLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(communicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(r2)
                            .addComponent(r1)
                            .addComponent(r3)))
                    .addGroup(communicationLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(communicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(r7)
                            .addComponent(r8)
                            .addComponent(r9)))
                    .addGroup(communicationLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(communicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(q1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(q2, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q3, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(q5, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(communicationLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(communicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(r10)
                            .addComponent(r11)
                            .addComponent(r12)))
                    .addGroup(communicationLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(communicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(r14)
                            .addComponent(r13)
                            .addComponent(r15)))
                    .addGroup(communicationLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(communicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(r6)
                            .addComponent(r4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(r5, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        communicationLayout.setVerticalGroup(
            communicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(communicationLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(q1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(r1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r3)
                .addGap(18, 18, 18)
                .addComponent(q2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r6)
                .addGap(18, 18, 18)
                .addComponent(q3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r9)
                .addGap(18, 18, 18)
                .addComponent(q4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r12)
                .addGap(18, 18, 18)
                .addComponent(q5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r15)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", communication);

        financial.setBackground(new java.awt.Color(255, 255, 255));

        lbudget.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lbudget.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbudget.setText("BUDGET");

        cbudget.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        cbudget.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5K-15K", "16K-30K", "30K-50K", "50K-1LACS", " " }));
        cbudget.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        cbudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbudgetActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel8.setText("NEXT");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout financialLayout = new javax.swing.GroupLayout(financial);
        financial.setLayout(financialLayout);
        financialLayout.setHorizontalGroup(
            financialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(financialLayout.createSequentialGroup()
                .addGroup(financialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(financialLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(lbudget, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190)
                        .addComponent(cbudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(financialLayout.createSequentialGroup()
                        .addGap(377, 377, 377)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        financialLayout.setVerticalGroup(
            financialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(financialLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(financialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbudget, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbudget, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(172, 172, 172)
                .addComponent(jLabel8)
                .addContainerGap(295, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", financial);

        mat.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("1. When faced with a complex problem , Do you :");

        jRadioButton1.setText("Feel overhelmed and avoid it ");

        jRadioButton2.setText("Break it down into smaller parts and tackle each one");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("Seek help from others immediately");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setText("Leader and organizer");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jRadioButton5.setText("Contributor and problem solver ");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        jRadioButton6.setText("Supporter and mediator");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setText("3. How do you handle stress ?");

        jRadioButton7.setText("Avoid stressful situations");

        jRadioButton8.setText("Manage stress through relaxation and techniques or exercise");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        jRadioButton9.setText("Share your feeelings with others and seek their support");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setText("4. When making decisions , you are more :");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("2. In a team project , which role do you naturally gravitate towards ?");

        jRadioButton10.setText("Analytical and logical ");

        jRadioButton11.setText("Intuitive and open to possibilties");

        jRadioButton12.setText("Collaborative and consensus-driven");

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setText("5. What do you value most in a career ? ");

        jRadioButton13.setText("Abilities and reliable income");

        jRadioButton14.setText("Creativity and personal fulfillment");

        jRadioButton15.setText("Making a meaningful difference in the world");

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setText("6. Which of the following areas interests you the most ?");

        jRadioButton16.setText("Science and technology");

        jRadioButton17.setText("Arts and humanities");

        jRadioButton18.setText("Social and humanitarian causes");

        javax.swing.GroupLayout matLayout = new javax.swing.GroupLayout(mat);
        mat.setLayout(matLayout);
        matLayout.setHorizontalGroup(
            matLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(matLayout.createSequentialGroup()
                .addGroup(matLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(matLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(matLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton3)))
                    .addGroup(matLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(matLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)))
                    .addGroup(matLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(matLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton5)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton6)))
                    .addGroup(matLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(matLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton7)
                            .addComponent(jRadioButton8)
                            .addComponent(jRadioButton9)))
                    .addGroup(matLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(matLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton11)
                            .addComponent(jRadioButton10)
                            .addComponent(jRadioButton12)))
                    .addGroup(matLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(matLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton14)
                            .addComponent(jRadioButton13)
                            .addComponent(jRadioButton15)))
                    .addGroup(matLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(matLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton17)
                            .addComponent(jRadioButton16)
                            .addComponent(jRadioButton18))))
                .addContainerGap(344, Short.MAX_VALUE))
        );
        matLayout.setVerticalGroup(
            matLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(matLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton18)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab5", mat);

        jPanel3.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 840, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt10markActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt10markActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt10markActionPerformed

    private void txtscholarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtscholarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtscholarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2ActionPerformed

    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r3ActionPerformed

    private void r5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r5ActionPerformed

    private void r6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r6ActionPerformed

    private void r7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3
        );
    }//GEN-LAST:event_jButton5ActionPerformed

    private void cbudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbudgetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbudgetActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void lbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbackMouseClicked
        // TODO add your handling code here:
        planfuture1 pf = new planfuture1();
        pf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbackMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        conclusion con = new conclusion();
        con.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(planyourfuture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(planyourfuture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(planyourfuture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(planyourfuture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new planyourfuture().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbookin;
    private javax.swing.JComboBox<String> cbudget;
    private javax.swing.JComboBox<String> ccontent;
    private javax.swing.JComboBox<String> ccultural;
    private javax.swing.JComboBox<String> cin;
    private javax.swing.JComboBox<String> combo12;
    private javax.swing.JComboBox<String> combod;
    private javax.swing.JPanel communication;
    private javax.swing.JComboBox<String> cout;
    private javax.swing.JPanel financial;
    private javax.swing.JLabel iconin;
    private javax.swing.JLabel iconq;
    private javax.swing.JPanel interest;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel l10mark;
    private javax.swing.JLabel l12mark;
    private javax.swing.JLabel lback;
    private javax.swing.JLabel lbook;
    private javax.swing.JLabel lbudget;
    private javax.swing.JLabel lcontent;
    private javax.swing.JLabel lcultural;
    private javax.swing.JLabel ldegree;
    private javax.swing.JLabel leducamp;
    private javax.swing.JLabel lindoor;
    private javax.swing.JLabel lolympaid;
    private javax.swing.JLabel loutdoor;
    private javax.swing.JLabel lscholar;
    private javax.swing.JPanel mat;
    private javax.swing.JLabel q1;
    private javax.swing.JLabel q2;
    private javax.swing.JLabel q3;
    private javax.swing.JLabel q4;
    private javax.swing.JLabel q5;
    private javax.swing.JPanel qualification;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r10;
    private javax.swing.JRadioButton r11;
    private javax.swing.JRadioButton r12;
    private javax.swing.JRadioButton r13;
    private javax.swing.JRadioButton r14;
    private javax.swing.JRadioButton r15;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JRadioButton r5;
    private javax.swing.JRadioButton r6;
    private javax.swing.JRadioButton r7;
    private javax.swing.JRadioButton r8;
    private javax.swing.JRadioButton r9;
    private javax.swing.JTextField txt10mark;
    private javax.swing.JTextField txt12mark;
    private javax.swing.JTextField txtdegree;
    private javax.swing.JTextField txteducamp;
    private javax.swing.JTextField txtolympaid;
    private javax.swing.JTextField txtscholar;
    // End of variables declaration//GEN-END:variables
}
