/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package intelligent.planning.pkgfor.academics;

/**
 *
 * @author Admin
 */
public class signuppage extends javax.swing.JFrame {

    /**
     * Creates new form signuppage
     */
    public signuppage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labelsignup = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        lusername = new javax.swing.JLabel();
        lpassword = new javax.swing.JLabel();
        txtuserame = new javax.swing.JTextField();
        typepassword = new javax.swing.JPasswordField();
        iconuser = new javax.swing.JLabel();
        iconpassword = new javax.swing.JLabel();
        btndone = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        labelsignup.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        labelsignup.setForeground(new java.awt.Color(0, 204, 255));
        labelsignup.setText("SIGN UP !");

        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\back.png")); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(labelsignup)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 37, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(labelsignup)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, -1));

        lusername.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lusername.setText("USERNAME");
        jPanel1.add(lusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        lpassword.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lpassword.setText("PASSWORD");
        jPanel1.add(lpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, 50));

        txtuserame.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtuserame.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtuserame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserameActionPerformed(evt);
            }
        });
        jPanel1.add(txtuserame, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 198, 35));

        typepassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        typepassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        typepassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typepasswordActionPerformed(evt);
            }
        });
        jPanel1.add(typepassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 198, 35));

        iconuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N
        jPanel1.add(iconuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        iconpassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/password.png"))); // NOI18N
        jPanel1.add(iconpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 52, -1));

        btndone.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btndone.setText("DONE");
        btndone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndoneMouseClicked(evt);
            }
        });
        jPanel1.add(btndone, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtuserameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserameActionPerformed

    private void typepasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typepasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typepasswordActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        homepage home = new homepage();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void btndoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndoneMouseClicked
        // TODO add your handling code here:
        planfuture1 plan = new planfuture1();
        plan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btndoneMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signuppage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signuppage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signuppage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signuppage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signuppage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JButton btndone;
    private javax.swing.JLabel iconpassword;
    private javax.swing.JLabel iconuser;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelsignup;
    private javax.swing.JLabel lpassword;
    private javax.swing.JLabel lusername;
    private javax.swing.JTextField txtuserame;
    private javax.swing.JPasswordField typepassword;
    // End of variables declaration//GEN-END:variables
}
